# Generated by Django 5.2.6 on 2025-09-16 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_areacomun_inquilino_propietario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tareamantenimiento',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Tarea de Mantenimiento', 'verbose_name_plural': 'Tareas de Mantenimiento'},
        ),
        migrations.RemoveField(
            model_name='tareamantenimiento',
            name='administrador_asigna',
        ),
        migrations.RemoveField(
            model_name='tareamantenimiento',
            name='fecha_limite',
        ),
        migrations.RemoveField(
            model_name='tareamantenimiento',
            name='personal_asignado',
        ),
        migrations.AddField(
            model_name='tareamantenimiento',
            name='costo_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo estimado de la tarea', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tareamantenimiento',
            name='titulo',
            field=models.CharField(blank=True, help_text='Título breve de la tarea', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tareamantenimiento',
            name='ubicacion_personalizada',
            field=models.CharField(blank=True, help_text='Descripción de ubicación si no es casa ni área común específica', max_length=200),
        ),
        migrations.AlterField(
            model_name='tareamantenimiento',
            name='area_comun',
            field=models.ForeignKey(blank=True, help_text='Área común donde se realizará el trabajo (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_mantenimiento', to='app.areacomun'),
        ),
        migrations.AlterField(
            model_name='tareamantenimiento',
            name='casa',
            field=models.ForeignKey(blank=True, help_text='Casa específica donde se realizará el trabajo (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_mantenimiento', to='app.casa'),
        ),
        migrations.AlterField(
            model_name='tareamantenimiento',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del trabajo a realizar', null=True),
        ),
        migrations.AlterField(
            model_name='tareamantenimiento',
            name='estado',
            field=models.CharField(choices=[('creada', 'Creada'), ('asignada', 'Asignada'), ('en_progreso', 'En progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='creada', max_length=20),
        ),
    ]
