# Generated by Django 5.2.6 on 2025-09-20 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propiedad',
            options={},
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='casa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='app.casa'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='fecha_adquisicion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='fecha_transferencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='propietario',
            field=models.ForeignKey(limit_choices_to={'rol__nombre': 'Propietario'}, on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='propiedad',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('casa',), name='una_propiedad_activa_por_casa'),
        ),
    ]
