# Generated by Django 5.2.6 on 2025-09-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_areacomun_inquilino_propietario_casa_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='fecha_certificacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
