# Generated by Django 5.2.6 on 2025-09-16 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_tareamantenimiento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField(help_text='Contenido del comunicado en formato texto plano o HTML')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, help_text='Cuando se hizo visible a los residentes', null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], default='borrador', max_length=20)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='comunicados_adjuntos/')),
                ('fecha_expiracion', models.DateTimeField(blank=True, help_text='Después de esta fecha, el comunicado ya no se muestra', null=True)),
                ('casa_destino', models.ForeignKey(blank=True, help_text='Si es nulo, va dirigido a todo el condominio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicados', to='app.casa')),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicados',
                'ordering': ['-fecha_publicacion', '-fecha_creacion'],
            },
        ),
    ]
