# Generated by Django 5.2.6 on 2025-09-15 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_administrador_fecha_certificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='casa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_residentes', to='app.casa'),
        ),
    ]
