# Generated by Django 5.2.6 on 2025-09-21 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_propiedad_options_alter_propiedad_activa_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagoreserva',
            name='reserva',
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha_pago'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='propiedad',
            options={'verbose_name': 'Propiedad', 'verbose_name_plural': 'Propiedades'},
        ),
        migrations.RemoveConstraint(
            model_name='propiedad',
            name='una_propiedad_activa_por_casa',
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='concepto',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='cuota',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='pagado_por',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='reserva',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='pagada',
        ),
        migrations.AddField(
            model_name='pago',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='pago',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo_pago',
            field=models.CharField(choices=[('cuota', 'Cuota'), ('reserva', 'Reserva de Área Común'), ('multa', 'Multa'), ('gasto_comun', 'Gasto Común'), ('otro', 'Otro')], default='cuota', max_length=20),
        ),
        migrations.AddField(
            model_name='pago',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, help_text='N° de transacción, comprobante, etc.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='activa',
            field=models.BooleanField(default=True, help_text='Indica si esta es la asignación de propiedad actual'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='casa',
            field=models.OneToOneField(help_text='Casa a la que pertenece esta propiedad', on_delete=django.db.models.deletion.CASCADE, related_name='propiedad', to='app.casa'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='fecha_adquisicion',
            field=models.DateField(auto_now_add=True, help_text='Fecha en que el propietario adquirió la propiedad'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='fecha_transferencia',
            field=models.DateField(blank=True, help_text='Fecha en que la propiedad fue transferida a otro propietario (si aplica)', null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='propietario',
            field=models.ForeignKey(help_text='Usuario propietario de la casa', limit_choices_to={'rol__nombre': 'Propietario'}, on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PagoReserva',
        ),
    ]
