# Generated by Django 5.2.6 on 2025-09-15 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_vehiculo_casa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residentes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='residente',
            constraint=models.UniqueConstraint(fields=('usuario', 'casa'), name='unique_usuario_casa'),
        ),
    ]
