# Generated by Django 5.2.6 on 2025-09-21 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_pagoreserva_reserva_alter_pago_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='object_id',
        ),
    ]
