# Generated by Django 5.2.6 on 2025-09-22 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_pago_content_type_pago_object_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
