# Generated by Django 5.2.6 on 2025-09-22 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidades', models.JSONField(default=list)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_contratacion', models.DateField(auto_now_add=True)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('horario_laboral', models.CharField(blank=True, help_text="Ej: 'Lunes a Viernes, 8am-5pm'", max_length=200)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'rol__nombre': 'Administrador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores_a_cargo', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_trabajador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
