# Generated by Django 5.2.6 on 2025-09-22 08:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_perfiltrabajador'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_completado', models.DateTimeField(blank=True, help_text='Cuando el trabajador marcó la tarea como completada', null=True)),
                ('estado_asignacion', models.CharField(choices=[('activa', 'Activa'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('reasignada', 'Reasignada')], default='activa', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre esta asignación', null=True)),
                ('asignado_por', models.ForeignKey(blank=True, help_text='Usuario que realizó la asignación (ej: administrador)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas_por_mi', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(help_text='Tarea que se está asignando', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='app.tareamantenimiento')),
                ('trabajador', models.ForeignKey(help_text='Perfil del trabajador al que se asigna la tarea', on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to='app.perfiltrabajador')),
            ],
            options={
                'verbose_name': 'Asignación de Tarea',
                'verbose_name_plural': 'Asignaciones de Tareas',
                'ordering': ['-fecha_asignacion'],
                'unique_together': {('tarea', 'trabajador', 'estado_asignacion')},
            },
        ),
    ]
