# Generated by Django 5.2.6 on 2025-09-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_asignaciontarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareamantenimiento',
            name='ubicacion_personalizada',
            field=models.CharField(blank=True, help_text='Descripción de ubicación si no es casa ni área común específica', max_length=200, null=True),
        ),
    ]
