# Generated by Django 5.2.6 on 2025-09-23 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_tareamantenimiento_ubicacion_personalizada'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_fcm', models.TextField(help_text='Token de Firebase Cloud Messaging para enviar notificaciones push', unique=True)),
                ('modelo_dispositivo', models.CharField(blank=True, help_text='Ej: iPhone 14, Samsung Galaxy S23', max_length=255, null=True)),
                ('sistema_operativo', models.CharField(blank=True, help_text='iOS, Android, etc.', max_length=50, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el dispositivo sigue recibiendo notificaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_conexion', models.DateTimeField(blank=True, help_text='Última vez que la app se conectó o renovó el token', null=True)),
                ('usuario', models.ForeignKey(help_text='Usuario propietario del dispositivo', on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispositivo Móvil',
                'verbose_name_plural': 'Dispositivos Móviles',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('cuerpo', models.TextField()),
                ('tipo', models.CharField(choices=[('seguridad', 'Seguridad'), ('finanzas', 'Finanzas'), ('areas_comunes', 'Áreas Comunes'), ('mantenimiento', 'Mantenimiento'), ('comunicado', 'Comunicado'), ('sistema', 'Sistema')], default='sistema', max_length=50)),
                ('estado', models.CharField(choices=[('enviada', 'Enviada'), ('entregada', 'Entregada'), ('leida', 'Leída'), ('fallida', 'Fallida')], default='enviada', max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, help_text='Cuando FCM confirma entrega', null=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('datos_adicionales', models.JSONField(blank=True, help_text='Payload adicional (ej: id de incidente, url, acción)', null=True)),
                ('intento_envio', models.PositiveSmallIntegerField(default=1)),
                ('dispositivo', models.ForeignKey(blank=True, help_text='Dispositivo al que se envió la notificación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_enviadas', to='app.dispositivomovil')),
                ('usuario', models.ForeignKey(help_text='Usuario destinatario de la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_push', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación Push',
                'verbose_name_plural': 'Notificaciones Push',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='IncidenteSeguridadIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acceso_no_autorizado', 'Acceso No Autorizado'), ('persona_desconocida', 'Persona Desconocida en Área Restringida'), ('vehiculo_mal_estacionado', 'Vehículo Mal Estacionado'), ('perro_suelto', 'Perro Suelto'), ('perro_haciendo_necesidades', 'Perro Haciendo Necesidades')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.CharField(help_text='Ej: Entrada principal, Torre A, Piscina', max_length=255)),
                ('imagen_evidencia', models.ImageField(blank=True, null=True, upload_to='incidentes/')),
                ('resuelto', models.BooleanField(default=False)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_resueltos', to=settings.AUTH_USER_MODEL)),
                ('notificacion_enviada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_asociados', to='app.notificacionpush')),
            ],
        ),
    ]
