# Generated by Django 5.2.6 on 2025-09-24 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_dispositivomovil_notificacionpush_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconocimientoPlaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_placa', models.ImageField(blank=True, null=True, upload_to='reconocimiento_placas/')),
                ('placa_detectada', models.CharField(blank=True, max_length=20, null=True)),
                ('accion_tomada', models.CharField(blank=True, choices=[('puerta_abierta', 'Puerta Abierta'), ('puerta_cerrada', 'Puerta Cerrada')], max_length=20, null=True)),
                ('estado', models.CharField(choices=[('procesando', 'Procesando'), ('placa_detectada', 'Placa Detectada'), ('sin_placa', 'No se detectó placa'), ('error_ia', 'Error en servicio de IA'), ('verificada', 'Verificada en sistema')], default='procesando', max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('respuesta_ia', models.JSONField(blank=True, null=True)),
                ('usuario_seguridad', models.ForeignKey(blank=True, limit_choices_to={'rol__nombre': 'Seguridad'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconocimientos_placa', to=settings.AUTH_USER_MODEL)),
                ('vehiculo_coincidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconocimientos', to='app.vehiculo')),
            ],
        ),
    ]
