# Generated by Django 5.2.6 on 2025-09-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_reconocimientoplaca'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacomun',
            name='es_de_pago',
            field=models.BooleanField(default=False, help_text='Indica si el alquiler de esta área común tiene un costo asociado.'),
        ),
    ]
