# Generated by Django 5.2.6 on 2025-09-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_areacomun_es_de_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacomun',
            name='costo_alquiler',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo por alquiler de esta área común, si aplica.', max_digits=8, null=True),
        ),
    ]
