# Generated by Django 5.2.6 on 2025-09-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_areacomun_costo_alquiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='pagada',
            field=models.BooleanField(default=False, help_text='Indica si la reserva ha sido pagada'),
        ),
    ]
