# Generated by Django 5.2.6 on 2025-09-28 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_reserva_pagada'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAccesoVehicular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_detectada', models.CharField(help_text='Placa identificada por el sistema OCR.', max_length=20)),
                ('acceso_exitoso', models.BooleanField(default=False, help_text='Indica si la placa fue reconocida y el acceso fue permitido.')),
                ('fecha_hora_intento', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales o razones del fallo.', null=True)),
                ('vehiculo_asociado', models.ForeignKey(blank=True, help_text='Vehículo registrado si el acceso fue exitoso. Nulo si no se encontró la placa.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.vehiculo')),
            ],
            options={
                'verbose_name': 'Registro de Acceso Vehicular',
                'verbose_name_plural': 'Registros de Acceso Vehicular',
                'ordering': ['-fecha_hora_intento'],
            },
        ),
        migrations.DeleteModel(
            name='ReconocimientoPlaca',
        ),
    ]
